# -*- coding: utf-8 -*-
"""DICE ROLL APPLICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Nq3oG4VC9g25NTBENtOzCdjSOkxsDuj
"""



"""# **CREATING A DICE ROLL APPLICATION USING PYTHON**
We'll be using: a) random.randint to simulate dice rolling events

                b)Capture and read user inputs using the built in input() function

                c)Display ASCII art representations of dice faces to the users with print()

                d)Manipulate python strings using methods like .center() and .join()

                e)Improve the design of a python progran with refactoring

# **Defining Project Requirements


1.   Identify the Key behaviours of the Dice rolling Application

*   Request the number of dice to roll
*   Read and verify the user's inputs
*   Simulate the randomness of a dice roll
*   Generate an ASCII diagram with the resulting dice faces
*   Display the results to the user
*   Exit Program

2.   Determinme the implementation Strategies you'll need to achieve them


*   Use python's built in input() function to capture user input
*   Define the function purse_input() to validate and handle input errors
*   Define the function roll_dice () that uses random.randint() to simulate dice rolls
*   Define the function generate_dice_faces_diagram() to display ASCII representations
*   Use print() function to display results and manage program flow
*   Implement the main loop(while True:) to allow multiple rounds or exit

*Introduction and imports*
"""

# 🎲 Dice Rolling Application
# Author: Sandra
# Description: Simulates rolling dice and displays ASCII faces for each roll.

import random  # For generating random dice rolls
import time    # For optional pauses to make it feel more realistic

"""*Parse and Validate Input*"""

def parse_input():
    """Ask the user how many dice to roll and validate the input."""
    while True:
        user_input = input("🎯 How many dice would you like to roll (1–6)? ")

        if user_input.strip().isdigit():  # check if the input is a number
            num_dice = int(user_input)

            if 1 <= num_dice <= 6:
                return num_dice
            else:
                print("⚠️ Please enter a number between 1 and 6.")
        else:
            print("⚠️ Invalid input. Please enter a number.")

"""*Simulate Rolling Dice*"""

def roll_dice(num_dice):
    """Simulate rolling 'num_dice' dice."""
    results = []
    for _ in range(num_dice):
        results.append(random.randint(1, 6))
    return results

"""*ASCII Faces for Dice*"""

# ASCII art representations for dice faces
DICE_ART = {
    1: ("+-------+",
        "|       |",
        "|   ●   |",
        "|       |",
        "+-------+"),
    2: ("+-------+",
        "| ●     |",
        "|       |",
        "|     ● |",
        "+-------+"),
    3: ("+-------+",
        "| ●     |",
        "|   ●   |",
        "|     ● |",
        "+-------+"),
    4: ("+-------+",
        "| ●   ● |",
        "|       |",
        "| ●   ● |",
        "+-------+"),
    5: ("+-------+",
        "| ●   ● |",
        "|   ●   |",
        "| ●   ● |",
        "+-------+"),
    6: ("+-------+",
        "| ●   ● |",
        "| ●   ● |",
        "| ●   ● |",
        "+-------+"),
}

"""*Generate Ascii Diagram*"""

def generate_dice_faces_diagram(dice_values):
    """Generate an ASCII diagram of dice faces side by side."""
    dice_faces = [DICE_ART[value] for value in dice_values]
    dice_faces_rows = [" ".join(row[i] for row in dice_faces) for i in range(5)]
    return "\n".join(dice_faces_rows)

"""Main Function To run Everything"""

def main():
    print("\n🎲 Welcome to the Dice Roller by Sandra! 🎲\n")
    time.sleep(0.5)

    while True:
        num_dice = parse_input()
        print("\nRolling the dice...\n")
        time.sleep(1)

        results = roll_dice(num_dice)
        dice_face_diagram = generate_dice_faces_diagram(results)

        print(dice_face_diagram)
        print(f"\n✨ You rolled: {', '.join(map(str, results))}\n")

        again = input("Roll again? (y/n): ").lower()
        if again != "y":
            print("\n👋 Thanks for playing! Goodbye!\n")
            break

# Run the program
main()